kind: ConfigMap
apiVersion: v1
metadata:
  name: iapp.k8s.irules
  namespace: f5-vxlan-lingque
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "f5-sni-lingque-svc",
          "servicePort": 80
        },
        "frontend": {
          "partition": "LingQue",
          "iapp": "/Common/a-test-iapp-irules-http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "iapp-irules-http",
            "trafficGroup":"/Common/traffic-group-1"
          },
          "iappVariables": {
            "pool__addr": "10.194.184.23",
            "pool__irules": "when HTTP_REQUEST {\n HTTP::redirect  http://10.1.1.1:1111\n}",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "9000"
          }
        }
      }
    }
