kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-sni-configmap
  namespace: f5-vxlan-lingque
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "f5-sni-lingque-svc",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /",
            "recv": "Welcome",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 443,
            "bindAddr": "10.1.1.1"
          },
          "partition": "LingQue",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileNames": ["Common/cert_1","Common/cert_2"]
          }
        }
      }
     }
